# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-22 15:00
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import profiles.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dt', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('candidate_name', models.CharField(max_length=250)),
                ('candidate_email', models.EmailField(max_length=250)),
                ('phone_number', models.CharField(max_length=15)),
                ('primary_skills', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=models.CharField())),
                ('experience', models.CharField(max_length=5, null=True)),
                ('current_ctc', models.CharField(max_length=8, null=True)),
                ('expected_ctc', models.CharField(max_length=8, null=True)),
                ('percent_rise', models.CharField(max_length=2, null=True)),
                ('current_company', models.CharField(blank=True, max_length=250, null=True)),
                ('notice_period', models.CharField(max_length=3, null=True)),
                ('resume_path', models.FileField(null=True, upload_to=profiles.models.get_profile_path)),
                ('resume_name', models.CharField(max_length=1000, null=True)),
                ('latest', models.BooleanField(default=True)),
                ('extracted_words', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=models.CharField())),
                ('location', models.CharField(max_length=30, null=True)),
                ('ready_for_change', models.NullBooleanField()),
                ('attached', models.BooleanField(default=False)),
                ('availability', models.CharField(default='No', max_length=4, null=True)),
                ('notes', models.CharField(max_length=1000, null=True)),
                ('current_role', models.CharField(default='', max_length=250, null=True)),
                ('alternate_phone_number', models.CharField(max_length=15, null=True)),
                ('added_for', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.Company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UnextractedProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_name', models.CharField(max_length=250)),
            ],
        ),
    ]
