# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-22 15:01
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import jobs.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0002_auto_20190322_2030'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dt', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('conversation_to', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=models.CharField())),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversation_created_by', to=settings.AUTH_USER_MODEL)),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dt', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('job_description', models.CharField(max_length=3000)),
                ('job_title', models.CharField(max_length=100, null=True)),
                ('primary_skills', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=models.CharField())),
                ('lead_time', models.SmallIntegerField(blank=True, null=True)),
                ('experience', models.CharField(max_length=5, null=True)),
                ('no_positions', models.SmallIntegerField(null=True)),
                ('created_for', models.CharField(max_length=20, null=True)),
                ('job_seq', models.IntegerField(null=True)),
                ('company_identifier', models.CharField(max_length=4, null=True)),
                ('reference_id', models.CharField(max_length=10, null=True)),
                ('job_type', models.CharField(default='FullTime', max_length=20, null=True)),
                ('location', models.CharField(max_length=30, null=True)),
                ('job_end_date', models.DateField(default='2019-05-06', null=True)),
                ('is_end_date', models.BooleanField(default=False)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='association_Job', to='company.Company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JobProfileAssociation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dt', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('resume', models.IntegerField(null=True)),
                ('final_status', models.CharField(default='Shared', max_length=20)),
                ('associated_profile_path', models.FileField(null=True, upload_to=jobs.models.content_associated_file_name)),
                ('candidate_name', models.CharField(max_length=250, null=True)),
                ('candidate_email', models.CharField(max_length=250, null=True)),
                ('primary_skills', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=models.CharField())),
                ('phone_number', models.CharField(max_length=15, null=True)),
                ('experience', models.CharField(max_length=5, null=True)),
                ('current_ctc', models.CharField(max_length=8, null=True)),
                ('expected_ctc', models.CharField(max_length=8, null=True)),
                ('current_company', models.CharField(blank=True, max_length=250, null=True)),
                ('notice_period', models.CharField(max_length=3, null=True)),
                ('location', models.CharField(max_length=30, null=True)),
                ('extracted_words', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=models.CharField())),
                ('cc_name', models.CharField(max_length=250, null=True)),
                ('vc_name', models.CharField(max_length=250, null=True)),
                ('receive_update_dt', models.DateField()),
                ('customer_checked', models.BooleanField(default=False)),
                ('status_remark', models.CharField(max_length=500, null=True)),
                ('notes', models.CharField(max_length=1000, null=True)),
                ('msg_read_status', models.SmallIntegerField(null=True)),
                ('next_level_status', models.CharField(max_length=250, null=True)),
                ('current_role', models.CharField(default='', max_length=250, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='association_company', to='company.Company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobprofileassociation_created_by', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='JobProfileAssociation_job', to='jobs.Job')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=25)),
                ('value', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dt', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.CharField(max_length=20)),
                ('future_state', models.SmallIntegerField(null=True)),
                ('level', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='jobprofileassociation',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='JobprofileAssociation_status', to='jobs.Status'),
        ),
        migrations.AddField(
            model_name='jobprofileassociation',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobprofileassociation_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobprofileassociation',
            name='vc_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='associated_vendor', to='company.Company'),
        ),
        migrations.AddField(
            model_name='job',
            name='job_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.Status'),
        ),
        migrations.AddField(
            model_name='job',
            name='parent_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Company'),
        ),
        migrations.AddField(
            model_name='job',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conversation',
            name='jpa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversation_resume', to='jobs.JobProfileAssociation'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversation_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
