# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-08 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20190330_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_end_date',
            field=models.DateField(default='2019-05-23', null=True),
        ),
    ]
