# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-11 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20190408_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_end_date',
            field=models.DateField(default='2019-06-25', null=True),
        ),
    ]
