SKILLS = ((1, 'Python'),(2, 'Jquery'),(3, 'React'),(4, 'Java'),(5,'.Net with MVC'), (6,'Active Directory'),(7,'Agile'),
          (8,'Angular JS'), (9,'Application Support'),(10,'Architects'),(11,'Backup'),(12,'Big data - Lead Engineer'),
          (13,'Business Analyst'), (14,'C# . Net – UI'),(15,'C++ And Embedded'), (16,'C++ with JAVA'),(17,'Citrix'),
          (18,'Cloud computing'),(19,'Control M'), (20,'Core Java'),(21,'Core Java + Spring+Hibernate'), (22,'CRM Dynamics'),
          (23,'Data Analyst'), (24,'Delphi Developer'), (25,'Dot Net'), (26,'Dot Net Engineer'), (27,'Dot Net Lead'),
          (28,'Dot Net with UI'),(29, 'Eclipse'),(30,'e-Commerce'),(31,'ETL & SQL Developer'), (32,'IBM Net Cool'),
          (33,'IBM Netcool'), (34,'IOS Developers'), (35,'Java with Angular JS 1, 2'),(36,'Java with Grails'),
          (37,'Java with Python'), (38,'Java with UI'), (39,'JD Edwards'),(40,'Linux Admin'), (41,'Linux/Unix Admin'),
          (42,'Mainframe'),(43,'Mobile Applications'),(44,'MongoDB'),(45,'MS CRM'),(46,'MS DX Techncal'), (47,'Network'),
          (48,'Networking/Telecom'), (49,'Nintex'),(50,'Node Js And React JS'), (51,'Oracle BRM'),(52,'Oracle DBA'),
          (53,'Oracle EBS'),(54,'Oracle Retail'),(55,'PEGA DEVELOPER'), (56,'Perl/Python + Kafka'), (57,'PHP DEVELOPER'),
          (58,'Preproduction Testing'), (59,'QA- Software Tester'),(60,'Release Management'),(61,'Sales Force'), (62,'Sales Manager'),
          (63,'SAP'),(64,'SAP Admin'), (65,'SAP ERP'),(66,'SAS'),(67,'Security'), (68,'ServiceNow Developer'),
          (69,'Share Point - Developer + Admin'),(70, 'SSAS'),(71,'Storage'), (72,'Telecom'),(73,'Teradata'), (74,'Testing'),
          (75,'TFS API Developer'),(76,'TFS Web UI Control Developer'),(77,'VC ++ Developer'),(78,'VMware'), (79,'Web Services'),
          (80,'Webmethods'), (81,'Windows Admin'), (82,'WordPress'),(83,'WordPress lead'), (84,'Xamarin Developer'),(85,'Other'))