# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-11 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20190322_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='interview_services',
            field=models.BooleanField(default=False),
        ),
    ]
